name: Check for Changes
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 9 * * *'

jobs:
  get-version:
    runs-on: ubuntu-latest
    env:
      FILES_TO_CHECK: "assets/resources/scriptlets.js|web_accessible_resources/|js/redirect-engine.js"
      UPSTREAM_URL: "https://github.com/gorhill/ublock.git"
    steps:
      - uses: actions/checkout@v2
      - name: Fetch release version
        run: |
          git remote add upstream ${UPSTREAM_URL}
          git fetch upstream && git diff --name-only --diff-filter AM HEAD..remotes/upstream/main > updatedfiles.txt
      - name: Check for modified files
        id: git-check
        run: echo ::set-output name=changes_present::$(if grep -qE "${FILES_TO_CHECK}" updatedfiles.txt; then echo 'true'; else echo 'false'; fi)
      - name: show files
        run: cat updatedfiles.txt
      - name: Have files changed
        if: steps.git-check.outputs.changes_present == 'false'
        run: exit 1