name: Generate Sync PR for Fork

on:
  workflow_run:
    workflows:
      - Check for Changes
    types:
      - completed

jobs:
  sync:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: tgymnich/fork-sync@v1.6.3
        with:
          owner: gorhill
          base: master
          head: master
          auto_approve: false
          ignore_fail: true