name: Check for Changes & Sync from Fork
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 9 * * *'

jobs:
  checkForChanges:
    runs-on: ubuntu-latest
    env:
      FILES_TO_CHECK: "assets/resources/scriptlets.js|web_accessible_resources/|js/redirect-engine.js"
      UPSTREAM_URL: "https://github.com/gorhill/ublock.git"
    outputs:
      changes: ${{ steps.git-check.outputs.changes_present }}
    steps:
      - uses: actions/checkout@v2
      - name: Fetch release version
        run: |
          git remote add upstream ${UPSTREAM_URL}
          git fetch upstream && git diff --name-only --diff-filter AM HEAD..remotes/upstream/master > updatedfiles.txt
      - name: Check for modified files
        id: git-check
        run: echo ::set-output name=changes_present::$(if grep -qE "${FILES_TO_CHECK}" updatedfiles.txt; then echo 'true'; else echo 'false'; fi)
      - name: show files
        run: cat updatedfiles.txt
      - name: Have files changed
        if: steps.checkForChanges.outputs.changes_present == 'false'
        run: echo "No changes needed to be synchronised"
  sync:
    needs: checkForChanges
    if: ${{ needs.checkForChanges.outputs.changes == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: tgymnich/fork-sync@v1.6.3
        with:
          owner: gorhill
          base: master
          head: master
          auto_approve: false
          ignore_fail: true